In [1]:
from training import *
from evaluate import *
from main import *
from load_glove import *
from data_helpers import *

import math

In [2]:
# Load word embeddings from glove file
glove_file = "/home/johannes/thesis_code/word_embeddings/glove.6B.100d.txt"
wiki_file = "/home/johannes/thesis_code/word_embeddings/wiki-news-300d-1M.vec"

em = load_wiki_embeddings(wiki_file)
#em = load_glove_embeddings(glove_file)
normalize_embeddings(em)

Done. 400000  words loaded!
Normalizing word embeddings

Done!



In [3]:
# Create training triples
data_file = "/home/johannes/thesis_code/ml_experimentation/data/training/1A.english.training.data.txt"
gold_file = "/home/johannes/thesis_code/ml_experimentation/data/training/1A.english.training.gold.txt"
train_data = read_train_examples(data_file, gold_file)


Generated  11779 positive training examples



In [12]:
# Replace words with their embeddings, if they exist, otherwise remove the word from the training data

train_embeddings = replace_with_embedding(train_data,em,1)

Created  8472  training examples with embeddings



In [13]:
transforms,b = train(em,train_embeddings, 30, True,0.01)

Loss, iter:  -0.6849555489312252 0 

Loss, iter:  -0.6585108950561535 1 

Loss, iter:  -0.6451002617046965 2 

Loss, iter:  -0.640563583494003 3 

Loss, iter:  -0.6383220781102082 4 

Loss, iter:  -0.6376534421241096 5 

Loss, iter:  -0.6366217459225992 6 

Loss, iter:  -0.6341735859727572 7 

Loss, iter:  -0.6352474426727924 8 

Loss, iter:  -0.6315837460022734 9 

Loss, iter:  -0.6315030822422376 10 

Loss, iter:  -0.6304586423455498 11 

Loss, iter:  -0.6332151551805322 12 

Loss, iter:  -0.6304534126899916 13 

Loss, iter:  -0.6281163079699928 14 

Loss, iter:  -0.6286124651481481 15 

Loss, iter:  -0.6335166308954636 16 

Loss, iter:  -0.6307477526255589 17 

Loss, iter:  -0.6320487330812669 18 

Loss, iter:  -0.6334276300448692 19 

Loss, iter:  -0.6313140448466726 20 

Loss, iter:  -0.6314328970254818 21 

Loss, iter:  -0.6242069996220218 22 

Loss, iter:  -0.6299476843181382 23 

Loss, iter:  -0.6313661290800007 24 

Loss, iter:  -0.6265305050141979 25 

Loss, iter:  -0.6283511

In [22]:
test_data_file = "/home/johannes/thesis_code/ml_experimentation/data/testing/1A.english.vocabulary.txt"
#test_data_file = "/home/johannes/thesis_code/ml_experimentation/data/training/1A.english.training.gold.txt"
te = read_test_examples(test_data_file)


Generated  218753  words for testing


In [23]:
word_embedding_pairs = add_embeddings(te,em)

Generated  67538  test examples with embeddings


In [24]:
words_only = [p[0] for p in word_embedding_pairs]

In [26]:
extract(em["volvo"],words_only,em, transforms,b,20)

67538


[(0.4748973869008166, 'criminogenic', 9),
 (0.4751796511016147, 'fibre-optic', 11),
 (0.4754489519129972, 'banishing', 11),
 (0.4756956706835574, 'superfast', 23),
 (0.4757641252896167, 'ricer', 11),
 (0.4758433398455166, '2223', 11),
 (0.4765256974665763, 'zapping', 0),
 (0.4766350810536224, 'stop-and-search', 9),
 (0.4766882819960126, 'depo', 0),
 (0.47702572551791367, 'looping', 0),
 (0.47723573576045963, 'stationing', 11),
 (0.4781358665768441, '2137', 11),
 (0.47821285856341667, 'flashing', 0),
 (0.4791991949984561, 'postcode', 9),
 (0.47965572179860105, 'blighting', 11),
 (0.4803540333282047, 'profiling', 23),
 (0.48040719954982486, 'top-of-the-range', 9),
 (0.48058121974916984, 'intercountry', 9),
 (0.4808164539258804, 'clickstream', 9),
 (0.48986035683433177, 'dossier', 16)]

In [20]:
#print(b)
transforms_ = [] #phi
for i in range(k):
    transforms_.append(np.identity(300) +np.random.normal(0, 0.5, [300,300]))

p_ = [np.dot(transforms_[i],em["blackfly"]).T for i in range(24)]
p = [np.dot(transforms[i],em["blackfly"]).T for i in range(24)]

for i in range(k):
    p[i] = p[i] / np.sqrt((np.sum(p[i]**2)))
    p_[i] = p_[i] / np.sqrt((np.sum(p_[i]**2)))

    

In [21]:
def sigmoid(x):
    return 1. / (1. + np.exp(-x))

s_ = np.dot(p_,em["insect"])
sigmoid_ = sigmoid(s_) 
rand_ = sigmoid_[np.argmax(sigmoid_)]


s = np.dot(p,em["insect"])
sigmoid = sigmoid(s) 
gud = sigmoid[np.argmax(sigmoid)]
print(rand_)
print(gud)

0.5612658686165467
0.5301037162970009


In [65]:

for q,h,t in train_embeddings:
    if (list(q),list(h),t) == (list(em["pollution"]),list(em["dirtiness"]),1):
        print("fak")

fak


In [41]:
"work" in em

True

In [34]:
# Write projection matrices and bias to file

matrix_fname = "matrix"
bias_fname = "bias"

matrix_file = open(matrix_fname, 'w+')
np.array(transforms).tofile(matrix_file)
matrix_file.close()

bias_file = open(bias_fname, 'w+')
np.array(b).tofile(bias_file)
bias_file.close()


In [17]:
# Read projection matrices and bias from file
matrix_fname = "matrix"
bias_fname = "bias"

matrix_file = open(matrix_fname, 'r')
transforms = np.fromfile(matrix_file)

bias_file = open(bias_fname, 'r')
b = np.fromfile(bias_file)

matrix_file.close()
bias_file.close()

In [ ]:
# T E S T I N G  B O I S

In [28]:
q = np.array([-1,1,2])
h = np.array([1,2,1])
phi = [np.array([[1.05,0.1,-0.1],[0.15,1.1,-0.05],[0.05,-0.1,0.95]]),np.array([[1.05,0.5,-0.1],[0.15,1.1,-0.05],[0.05,-0.1,0.95]])]

def sigmoid(x):
    return 1. / (1. + np.exp(-x))

def normm(p):
    p = p / np.sqrt((np.sum(p**2)))
    return p

In [49]:
p = [np.dot(phi[i],q).T for i in range(2)]

In [50]:
p[0] = normm(p[0])
p[1] = normm(p[1])

p

[array([-0.50885454,  0.37610988,  0.77434386]),
 array([-0.40757786,  0.38362715,  0.82867997])]

In [51]:
s = np.dot(p,h)

In [52]:
s

array([1.01770908, 1.18835643])

In [53]:
sigmoids = sigmoid(s)

In [54]:
sigmoids

array([0.73452612, 0.76644698])

In [55]:
maxsim = np.argmax(sigmoids)
y = sigmoids[maxsim]
x = p[maxsim]

In [56]:
loss = 0*np.log(y) - (np.subtract(1,0)*np.log(np.subtract(1,y)))
gradient = np.dot(x.T,loss)
gradient

array([-0.5927593 ,  0.55792669,  1.20518755])

In [57]:
prev_theta = phi[maxsim]
#print("Before: ", prev_theta)
phi[maxsim] = np.subtract(prev_theta, np.multiply(0.01,gradient))

In [58]:
phi

[array([[ 1.05,  0.1 , -0.1 ],
        [ 0.15,  1.1 , -0.05],
        [ 0.05, -0.1 ,  0.95]]),
 array([[ 1.06719644,  0.48223391, -0.13743251],
        [ 0.16719644,  1.08223391, -0.08743251],
        [ 0.06719644, -0.11776609,  0.91256749]])]

In [82]:
(np.array([1,2,2]) == np.array([1,2,2])).all()

True

In [29]:
np.gradient(np.array([1,2,3,4,-1]))

array([ 1.,  1.,  1., -2., -5.])